import { Article } from "./article";
import { CreativeWork } from "./creative-work";
import { ImageObject } from "./image-object";
import { Person } from "./person";
import { Place } from "./place";
import { QuantitativeValue } from "./quantitative-value";
import { Thing } from "./thing";

export type Organization = Thing & {
    //acceptedPaymentMethod?: LoanOrCredit | PaymentMethod;
    actionableFeedbackPolicy?: CreativeWork | URL;
    //address?: PostalAddress | string;
    //agentInteractionStatistic?: InteractionCounter;
    //aggregateRating?: AggregateRating;
    alumni?: Person;
    //areaServed?: AdministrativeArea | GeoShape | Place | string;
    award?: string;
    //brand?: Brand | Organization;
    //contactPoint?: ContactPoint;
    correctionsPolicy?: CreativeWork | URL;
    department?: Organization;
    dissolutionDate?: Date;
    diversityPolicy?: CreativeWork | URL;
    diversityStaffingReport?: Article | URL;
    duns?: string;
    email?: string;
    employee?: Person;
    ethicsPolicy?: CreativeWork | URL;
    event?: Event;
    faxNumber?: string;
    founder?: Person;
    foundingDate?: Date;
    foundingLocation?: Place;
    funder?: Organization | Person;
    //funding?: Grant;
    globalLocationNumber?: string;
    //hasCertification?: Certification;
    //hasCredential?: EducationalOccupationalCredential;
    hasGS1DigitalLink?: URL;
    //hasMerchantReturnPolicy?: MerchantReturnPolicy;
    //hasOfferCatalog?: OfferCatalog;
    hasPOS?: Place;
    //interactionStatistic?: InteractionCounter;
    isicV4?: string;
    iso6523Code?: string;
    //keywords?: DefinedTerm | string | URL;
    knowsAbout?: string | Thing | URL;
    //knowsLanguage?: Language | string;
    legalName?: string;
    leiCode?: string;
    //location?: Place | PostalAddress | string | VirtualLocation;
    logo?: ImageObject | URL;
    //makesOffer?: Offer;
    member?: Organization | Person;
    //memberOf?: Organization | ProgramMembership;
    naics?: string;
    //nonprofitStatus?: NonprofitType;
    numberOfEmployees?: QuantitativeValue;
    //ownershipFundingInfo?: AboutPage | CreativeWork | string | URL;
    //owns?: OwnershipInfo | Product;
    parentOrganization?: Organization;
    publishingPrinciples?: CreativeWork | URL;
    //review?: Review;
    //seeks?: Demand;
    slogan?: string;
    sponsor?: Organization | Person;
    subOrganization?: Organization;
    taxID?: string;
    telephone?: string;
    unnamedSourcesPolicy?: CreativeWork | URL;
    vatID?: string;
  };
  