type Person = {
    additionalName?: string;
    //address?: PostalAddress | string;
    affiliation?: Organization;
    //agentInteractionStatistic?: InteractionCounter;
    //alumniOf?: EducationalOrganization | Organization;
    award?: string;
    birthDate?: Date;
    //birthPlace?: Place;
    //brand?: Brand | Organization;
    callSign?: string;
    children?: Person;
    colleague?: Person | URL;
    //contactPoint?: ContactPoint;
    deathDate?: Date;
    //deathPlace?: Place;
    duns?: string;
    email?: string;
    familyName?: string;
    faxNumber?: string;
    follows?: Person;
    funder?: Organization | Person;
    //funding?: Grant;
    //gender?: GenderType | string;
    givenName?: string;
    globalLocationNumber?: string;
    //hasCertification?: Certification;
    //hasCredential?: EducationalOccupationalCredential;
    //hasOccupation?: Occupation;
    //hasOfferCatalog?: OfferCatalog;
    //hasPOS?: Place;
    //height?: Distance | QuantitativeValue;
    //homeLocation?: ContactPoint | Place;
    honorificPrefix?: string;
    honorificSuffix?: string;
    //interactionStatistic?: InteractionCounter;
    isicV4?: string;
    //jobTitle?: DefinedTerm | string;
    knows?: Person;
    knowsAbout?: string | Thing | URL;
    //knowsLanguage?: Language | string;
    //makesOffer?: Offer;
    //memberOf?: Organization | ProgramMembership;
    naics?: string;
    //nationality?: Country;
    //netWorth?: MonetaryAmount | PriceSpecification;
    //owns?: OwnershipInfo | Product;
    parent?: Person;
    performerIn?: Event;
    publishingPrinciples?: CreativeWork | URL;
    relatedTo?: Person;
    //seeks?: Demand;
    sibling?: Person;
    sponsor?: Organization | Person;
    spouse?: Person;
    taxID?: string;
    telephone?: string;
    vatID?: string;
    weight?: QuantitativeValue;
    //workLocation?: ContactPoint | Place;
    worksFor?: Organization;
  };
  