type Product = Thing & {
    additionalProperty?: PropertyValue;
    //aggregateRating?: AggregateRating;
    asin?: string | URL;
    //audience?: Audience;
    award?: string;
    //brand?: Brand | Organization;
    //category?: CategoryCode | PhysicalActivityCategory | string | Thing | URL;
    color?: string;
    colorSwatch?: ImageObject | URL;
    countryOfAssembly?: string;
    countryOfLastProcessing?: string;
    //countryOfOrigin?: Country;
    //depth?: Distance | QuantitativeValue;
    //funding?: Grant;
    gtin?: string | URL;
    gtin12?: string;
    gtin13?: string;
    gtin14?: string;
    gtin8?: string;
    //hasAdultConsideration?: AdultOrientedEnumeration;
    //hasCertification?: Certification;
    //hasEnergyConsumptionDetails?: EnergyConsumptionDetails;
    hasGS1DigitalLink?: URL;
    hasMeasurement?: QuantitativeValue;
    //hasMerchantReturnPolicy?: MerchantReturnPolicy;
    //height?: Distance | QuantitativeValue;
    inProductGroupWithID?: string;
    isAccessoryOrSparePartFor?: Product;
    isConsumableFor?: Product;
    isFamilyFriendly?: boolean;
    //isRelatedTo?: Product | Service;
    //isSimilarTo?: Product | Service;
    //isVariantOf?: ProductGroup | ProductModel;
    //itemCondition?: OfferItemCondition;
    //keywords?: DefinedTerm | string | URL;
    logo?: ImageObject | URL;
    //manufacturer?: Organization;
    material?: Product | string | URL;
    mobileUrl?: string;
    //model?: ProductModel | string;
    mpn?: string;
    //negativeNotes?: ItemList | ListItem | string | WebContent;
    nsn?: string;
    //offers?: Demand | Offer;
    //pattern?: DefinedTerm | string;
    //positiveNotes?: ItemList | ListItem | string | WebContent;
    productID?: string;
    productionDate?: Date;
    purchaseDate?: Date;
    releaseDate?: Date;
    //review?: Review;
    //size?: DefinedTerm | QuantitativeValue | SizeSpecification | string;
    sku?: string;
    slogan?: string;
    weight?: QuantitativeValue;
    //width?: Distance | QuantitativeValue;
  };
  