type SemEvent = Thing & {
    about?: Thing;
    actor?: Person;
    //aggregateRating?: AggregateRating;
    //attendee?: Organization | Person;
    //audience?: Audience;
    //composer?: Organization | Person;
    //contributor?: Organization | Person;
    director?: Person;
    //doorTime?: DateTime | Time;
    //duration?: Duration;
    endDate?: Date //| DateTime;
    //eventAttendanceMode?: EventAttendanceModeEnumeration;
    //eventSchedule?: Schedule;
    //eventStatus?: EventStatusType;
    //funder?: Organization | Person;
    //funding?: Grant;
    //inLanguage?: Language | string;
    isAccessibleForFree?: boolean;
    //keywords?: DefinedTerm | string | URL;
    //location?: Place | PostalAddress | string | VirtualLocation;
    maximumAttendeeCapacity?: number;
    maximumPhysicalAttendeeCapacity?: number;
    maximumVirtualAttendeeCapacity?: number;
   // offers?: Demand | Offer;
    //organizer?: Organization | Person;
    //performer?: Organization | Person;
    previousStartDate?: Date;
    recordedIn?: CreativeWork;
    remainingAttendeeCapacity?: number;
    //review?: Review;
    //sponsor?: Organization | Person;
    startDate?: Date //| DateTime;
    subEvent?: Event;
    superEvent?: Event;
    //translator?: Organization | Person;
    typicalAgeRange?: string;
    workFeatured?: CreativeWork;
    workPerformed?: CreativeWork;
  };
  